### ISSUE TITLE
event.h报错

### ISSUE THREAD

**Issue by UranusITS** [cqmoe/cqcppsdk#1]
一开始文件还可以生成，但是在我加了几行代码后显示`event.h`出现各种错误。我重新下载了`cqcppsdk`的所有文件并放入`extern`文件夹，还是显示同样的报错。
![报错信息](https://user-images.githubusercontent.com/38391284/73130564-5ca54200-4035-11ea-8f96-339d6eae40c5.png)
![新增的代码](https://user-images.githubusercontent.com/38391284/73130566-79417a00-4035-11ea-9baf-220000073392.png)
更改后的头文件：
```cpp
#include<iostream>
#include<set>
#include<sstream>
#include<cstdio>
#include<cmath>
#include<cstdlib>
#include<ctime>
#include<urlmon.h>
#include<string>
#include<fstream>

#include<cqcppsdk/cqcppsdk.h>

#pragma comment(lib,"urlmon.lib")
```

**Comment by stdrc** [comment]
试下把 `#include<cqcppsdk/cqcppsdk.h>` 放到最上面，因为 `urlmon.h` 里可能有名字污染了全局作用域

**Comment by UranusITS** [comment]
解决了，谢谢
