### ISSUE TITLE
引用windows.h时报错

### ISSUE THREAD

**Issue by sevenshape** [cqmoe/cqcppsdk#20]

**Comment by stdrc** [comment]
报错信息来一点？（不然我凭空猜嘛😂

**Comment by sevenshape** [comment]
[build] C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\rpcndr.h(192): error C2872: “byte”: 不明确的符号
[build] C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\rpcndr.h(191): note: 可能是“unsigned char byte”
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\cstddef(29): note: 或    “std::byte”
[build] C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\rpcndr.h(962): error C2872: “byte”: 不明确的符号
[build] C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\rpcndr.h(191): note: 可能是“unsigned char byte”

**Comment by ExerciseBook** [comment]
#include<windows.h> 放到最后引用

**Comment by sevenshape** [comment]
全局搜索windows.h找到了段代码解决了
#ifdef WIN32
#define WIN32_LEAN_AND_MEAN
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <Windows.h>
#undef IGNORE // 避免名字冲突
#include <fcntl.h>
#include <io.h>
#endif
