### ISSUE TITLE
有没有纯c语言版本

### ISSUE THREAD

**Issue by springeye** [cqmoe/cqcppsdk#23]
大佬，有没有纯c语言版本的sdk！

**Comment by ExerciseBook** [comment]
来了来了，不过可能需要你手动整理一下？（其实我之前整理过一个版本）

https://github.com/Tnze/CoolQ-Golang-SDK/blob/df4beb0205c7335243784876a19dcf104e969521/cqp/apis.c

**Comment by ExerciseBook** [comment]
[20200219_c.zip](https://github.com/cqmoe/cqcppsdk/files/4579043/20200219_c.zip)

如果喜欢的话就拿走吧。不是什么大问题。

**Comment by springeye** [comment]
@ExerciseBook 哎呀我去。我知道有一个GOlang版本，但是我不知道它居然就用的C版本。太好了，太感谢了。

**Comment by ExerciseBook** [comment]
不客气
如果你有空的话，可以把我刚刚的压缩包整理一下，把缺了的api和调用方法都补齐。qwq
