### ISSUE TITLE
跨平台vcpkg支持无效

### ISSUE THREAD

**Issue by YuiTH** [cqmoe/cqcppsdk#24]
macOS使用mingw i686跨平台编译demo通过
按照SDK上的，在macOS上装了一个vcpkg然后想指定triplet 为x86-windows-static-md(似乎要求的动态CRT配置在vcpkg中自带了)
但是在安装库的时候出现了错误Cannot build windows triplets from non-windows.
vcpkg是否无法跨平台编译？还是需要额外的步骤指示vcpkg识别mingw工具链？

**Comment by stdrc** [comment]
@YuiTH 之前似乎有用户折腾过在 vcpkg 用 mingw，但并没有成功

**Comment by YuiTH** [comment]
> @YuiTH 之前似乎有用户折腾过在 vcpkg 用 mingw，但并没有成功

唔，短期内应该是没什么好办法了，我只能回win去用VS开发了。
可以的话希望在文档的vcpkg页面加一个“暂时不支持跨平台编译”的说明，我看文档里还有
`./bootstrap-vcpkg.sh # Linux`
的一行，我就以为您在Linux上试用过了……加个说明也算节约后来者时间吧。
另外vcpkg的master现在有一个新的triplet提供了库要求的
`set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)`配置，名叫x86-windows-static-md，如果是您需要的triplet的话可以改用这个而不是手动修改x86-windows-static的cmake文件，方便版本移植。

**Comment by stdrc** [comment]
@YuiTH 感谢建议，另外，那个 x86-windows-static-md 我看在 community 目录里面，使用起来和 x86-windows-static 是一样的 lib-name:x86-windows-static 吗（手头没有 vcpkg，不方便测试）

**Comment by YuiTH** [comment]
> @YuiTH 感谢建议，另外，那个 x86-windows-static-md 我看在 community 目录里面，使用起来和 x86-windows-static 是一样的 lib-name:x86-windows-static 吗（手头没有 vcpkg，不方便测试）

我也不是很了解vcpkg，我去找个windows跑下试试看。另外x86-windows-static本身也被放进community去了……我没跟他们的git不知道是什么情况。

**Comment by YuiTH** [comment]
> @YuiTH 感谢建议，另外，那个 x86-windows-static-md 我看在 community 目录里面，使用起来和 x86-windows-static 是一样的 lib-name:x86-windows-static 吗（手头没有 vcpkg，不方便测试）

去测了下，这里直接lib-name:x86-windows-static-md拉的就是和之前x86-windows-static一样的包，一个triplet我猜应该是对应一组编译选项，x86-windows-static和-md拉包的时候拉的都是x86架构的包，因为triplet文件只改了一个dynamic而已。

**Comment by stdrc** [comment]
感谢测试，文档已经更新
