### ISSUE TITLE
FAKE_COOLQ_ROOT_DIR建议改为非中文路径，以方便调试，谢谢

### ISSUE THREAD

**Issue by jimowutong42** [cqmoe/cqcppsdk#26]
https://github.com/cqmoe/cqcppsdk/blob/28ff31882f810c2fe06bc282373df560eb9a409d/src/dev_mode/mock.hpp#L27
https://github.com/cqmoe/cqcppsdk/blob/28ff31882f810c2fe06bc282373df560eb9a409d/src/dev_mode/mock.hpp#L29

CoolQ Fake

**Comment by ExerciseBook** [comment]
我感觉 @richardchien 故意这样干的，用来折腾在带中文环境下的那种情况。

因为酷Q本身的压缩包都是 `酷Q Air.zip` 和 `酷Q Pro.zip` 这样的格式，而且大部分的插件用户都不会主动修改。因而在 SDK 中保留了这种特性。



需要注意的是：在 `string.hpp` 中提供了 UTF8 和 系统默认编码 互转的函数，Windows 的路径采用的是系统默认编码，因而可能需要在读写路径的时候手动转换一下。

**Comment by jimowutong42** [comment]
已解决
`cq::utils::s2ws(“中文路径”)`

**Comment by stdrc** [comment]
> cq::utils::s2ws(“中文路径”)

除了这个，也可以使用 `std::filesystem::u8path("中文路径")`

**Comment by jimowutong42** [comment]
> 已解决
> `cq::utils::s2ws(“中文路径”)`

@richardchien cq::utils::ws2s和cq::utils::s2ws这两个函数在MSVC2017上报C4996警告，看起来是C++17不提倡的做法：

'std::codecvt_utf8<wchar_t,1114111,0>': warning STL4017: std::wbuffer_convert, std::wstring_convert, and the <codecvt> header (containing std::codecvt_mode, std::codecvt_utf8, std::codecvt_utf16, and std::codecvt_utf8_utf16) are deprecated in C++17. (The std::codecvt class template is NOT deprecated.) The C++ Standard doesn't provide equivalent non-deprecated functionality; consider using MultiByteToWideChar() and WideCharToMultiByte() from <Windows.h> instead. You can define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

'std::wstring_convert<std::codecvt_utf8<wchar_t,1114111,0>,wchar_t,std::allocator<wchar_t>,std::allocator<char>>::to_bytes': warning STL4017: std::wbuffer_convert, std::wstring_convert, and the <codecvt> header (containing std::codecvt_mode, std::codecvt_utf8, std::codecvt_utf16, and std::codecvt_utf8_utf16) are deprecated in C++17. (The std::codecvt class template is NOT deprecated.) The C++ Standard doesn't provide equivalent non-deprecated functionality; consider using MultiByteToWideChar() and WideCharToMultiByte() from <Windows.h> instead. You can define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

**Comment by stdrc** [comment]
@jslyxyc 问题不大，因为 c++17 deprecated 了 codecvt 库，但目前还没替代，还能用
